Scheme=scheme
STEXLIB=..

# define default document pathname here
# override on command line with 'make x=newdoc'
x = stex

# define latex processor: latex or pdflatex
latex = pdflatex

# define stex macro files here
stexmacrofiles = 

# list bibliography files here
bib =

# define index if an index is to be generated
# index=yes

# override katex variables here if desired
KATEX_CSS=no # see comment in stex.katex-css-link

include $(STEXLIB)/Mf-stex

# define or override suffixes here

# define any additional targets here

# define any dependencies here

# define cleanup targets here:

$(x).clean:
	-rm -f $x.rawsst

$(x).reallyclean:

$(x).reallyreallyclean:
